### ISSUE TITLE
No use of thirdweb???

### ISSUE THREAD

**Issue by Reedyuk** [Shobhit1338/react-abstract-nft-collection#2]
You mentioned thirdweb but i cannot see it in the source code.
Am i missing something here?

**Comment by Shobhit1338** [comment]
> You mentioned thirdweb but i cannot see it in the source code.
> Am i missing something here?

I used thirdweb to create my NFT project API and thus publish it on OpenSea. Then i called the API from OpenSea website in json format.

**Comment by Reedyuk** [comment]
Ah ok, makes sense. I thought you were using their sdk.

Sent from my iPhone

On 15 Jan 2022, at 22:10, Shobhit Gupta ***@***.***> wrote:

﻿

You mentioned thirdweb but i cannot see it in the source code.
Am i missing something here?

I used thirdweb to create my NFT project API and thus publish it on OpenSea. Then i called the API from OpenSea website in json format.
